### ISSUE TITLE
Mattermost 3.4

### ISSUE THREAD

**Issue by cduverne** [jasl8r/docker-mattermost#10]
Hello @jasl8r !

Do you intend to build a docker image for mattermost 3.4 by any chance ?
May I help ?

Thanks a lot for bringing this.
Cyrille

**Comment by funkyfuture** [comment]
i tried to build mattermost on alpine 3.4, but it fails. here's the [build log](http://pastebin.com/A37AbXDa). 

as i'm absolutely unfamiliar with anything js-related, thus the log isn't helpful to me. hints what may be wrong are appreciated.

**Comment by cduverne** [comment]
Just a rough search, but could it be related to this : https://github.com/mijime/docker-mattermost/issues/17 ?

**Comment by jasl8r** [comment]
I've dropped the ball on this a bit.  I'll have a 3.4 build up in a few days.

**Comment by funkyfuture** [comment]
impressive image concerning sophistication, btw.

**Comment by cduverne** [comment]
@jasl8r may I be of any help ?

**Comment by jasl8r** [comment]
Just pushed tag 3.4.0.  Sorry about the lack of updates.
