### ISSUE TITLE
Upgrade from 2.2.0 to 3.4.0 causes container to exit

### ISSUE THREAD

**Issue by mwilmes** [jasl8r/docker-mattermost#13]
Upgrade from 2.2.0 to 3.4.0 causes the mattermost container to exit at step:

```
+ [[ 3.4.0 != 3.4.0 ]]
+ echo 3.4.0
+ ./bin/platform -config /opt/mattermost/config/config.json
<container exits>
```

Upgrade to 3.1.0 however worked seamlessly. During the same time the linked mysql container reports "Got an error reading communication packets" for user mattermost.

**Comment by jasl8r** [comment]
I'm seeing this too.  I'm not sure what's happening there, it's possibly related to this utf8 / utf8mb4 issue here: http://stackoverflow.com/questions/3513773/change-mysql-default-character-set-to-utf-8-in-my-cnf

I'll have to look into it more.

If you update to 3.1.0 and then 3.4.0 does it work?

**Comment by jasl8r** [comment]
Mattermost must be upgraded from version 2.2.0 to either 3.0.2 or 3.1.0 before further upgrading.  I just pushed 3.4.0-1 to address this.  You can resolve this by first running jasl8r/mattermost:3.1.0 and then jasl8r/mattermost:3.4.0-1
