### ISSUE TITLE
no logging of the mattermost container

### ISSUE THREAD

**Issue by funkyfuture** [jasl8r/docker-mattermost#15]
i'm currently trying to troubleshoot why a mattermost container doesn't send mails. but i'm kinda blindfolded here as it doesn't log anything. this is the output i get with `docker-compose logs`:

```
mattermost_1  | Initializing mattermost...
mattermost_1  | Initializing datadir...
mattermost_1  | Initializing logdir...
mattermost_1  | Installing configuration templates...
mattermost_1  | Configuring mattermost...
mattermost_1  | Configuring mattermost database...
mattermost_1  | Configuring SMTP...
mattermost_1  | Configuring GitLab..
mattermost_1  | Configuring new Mattermost installation...
```

this is only followed by a series of postgres messages like this:

```
postgres_1    | ERROR:  relation "systems" does not exist at character 19
postgres_1    | STATEMENT:  SELECT Value FROM Systems WHERE Name='Version'
postgres_1    | ERROR:  relation "idx_teams_name" does not exist
postgres_1    | STATEMENT:  SELECT $1::regclass
```

i can interact with the webinterface so far that i can create the initial user, but i don't receive an email and there is nothing logged by the mattermost container.

is there a way to raise the logging verbosity?

**Comment by funkyfuture** [comment]
i looked into it and it's of course pretty simple. i would contribute the needed changes.

but i would actually propose to change the default behaviour so the logs go to the console and not to a log file as this is the usual way afaik how containers should log. as there are different logging handlers / plugins available that take it from there.

**Comment by jostyee** [comment]
@funkyfuture Mattermost support console logging https://github.com/mattermost/platform/blob/master/config/config.json#L75
you can add a property setting if you want it.

**Comment by funkyfuture** [comment]
yes, but i'm proposing to change the default logging target to the console as this is the standard that will be handled by the different available logging drivers.
