### ISSUE TITLE
MM "looses" parts of its config from time to time

### ISSUE THREAD

**Issue by trippel** [jasl8r/docker-mattermost#8]
I don't know whether this is related to this docker image in particular or to mm in general. My installation looses parts of its settings from time to time, which I need to reconfigure via System Console if that happens.

Didn't find any related error messages.

Any idea?

**Comment by jasl8r** [comment]
This docker image only supports configuration by environment variables.  All settings changed by the system console will be lost on restart.  This should be added to the README.

**Comment by trippel** [comment]
Thanks, I can live with that. :)
